name: Domain Configuration
description: 'Allows domain specific configuration.'
type: module
package: Domain
# version: VERSION
# core: 8.x
dependencies:
  - domain

# Information added by Drupal.org packaging script on 2017-04-23
version: '8.x-1.0-alpha9'
core: '8.x'
project: 'domain'
datestamp: 1492972752
